# Generated by Django 2.2 on 2021-02-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Stack'),
        ),
    ]
