# Generated by Django 2.2 on 2021-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210205_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(to='api.Stack'),
        ),
    ]
