# Generated by Django 2.2 on 2021-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210205_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
