# Generated by Django 2.2 on 2021-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stack',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
