# Generated by Django 2.2 on 2021-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210224_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['order'], 'verbose_name': 'Stack', 'verbose_name_plural': 'Stacks'},
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
