# Generated by Django 2.2.19 on 2021-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210310_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
