# Generated by Django 2.2.19 on 2021-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210314_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_small',
            new_name='thumbnail',
        ),
    ]
